version: "3"

services:

        nginx:
                container_name: nginx
                build: ./nginx
                restart: always
                image: docker-server/nginx
                ports:
                  - "80:80"
                volumes:
                  - ./server_dev:/srv/docker-server
                  - ./log:/var/log/nginx
                depends_on:
                  - django

        django:
                container_name: django
                build: ./airhelper-backend
                image: docker-server/django
                restart: always
                command: uwsgi --ini uwsgi.ini
                volumes:
                   - ./server_dev:/srv/docker-server
                   - ./log:/var/log/uwsgi
