version: "3"

services:
  django:
    build:
      context: .
      dockerfile: Dockerfile-prod
    ports:
      - "8000:8000"
    volumes:
      - .:/airhelper-backend
    command: gunicorn backend.wsgi:application --bind 0.0.0.0:8000
    expose:
      - "8000"

  nginx:
    image: nginx:latest # nginx 서비스에서 사용할 도커 이미지
    ports:
      - "80:80"
    volumes:
      - .:/airhelper-backend
      - ./config/nginx:/etc/nginx/conf.d
    depends_on: # 서비스 간의 종속성 표현
      - django