version: "3"

services:

        nginx:
                container_name: nginx
                build: ./nginx
                restart: always
                image: ./nginx
                ports:
                  - "80:80"
                volumes:
                  - ./:/srv/docker-server
                  - ./:/var/log/nginx
                depends_on:
                  - django

        django:
                container_name: django
                build:
                  context: ./
                  dockerfile: Dockerfile-prod
                image: ./
                restart: always
                command: uwsgi --ini uwsgi.ini
                volumes:
                   - ./server_dev:/srv/docker-server
                   - ./log:/var/log/uwsgi
