
"""
Django settings for backend project.
Generated by 'django-admin startproject' using Django 3.1.3.
For more information on this file, see
https://docs.djangoproject.com/en/3.1/topics/settings/
For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.1/ref/settings/
"""

from pathlib import Path
from .base import *
import os
import json


# Database
# https://docs.djangoproject.com/en/3.2/ref/settings/#databases
if sys.argv[0] == 'pytest':
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
        }
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': 'airhelperdev',
            'USER': 'airhelper',
            'PASSWORD': 'airhelper',
            'HOST': 'psqldb',
            'PORT': 5432,
        }
    }
