
"""
Django settings for backend project.
Generated by 'django-admin startproject' using Django 3.1.3.
For more information on this file, see
https://docs.djangoproject.com/en/3.1/topics/settings/
For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.1/ref/settings/
"""

from pathlib import Path
from .base import *
import os
import json


# Database
# https://docs.djangoproject.com/en/3.2/ref/settings/#databases'
print('우와...', os.getenv('GITHUB') == None)
if os.getenv('GITHUB') is None:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': 'airhelperdev',
            'USER': 'airhelper',
            'PASSWORD': 'airhelper',
            'HOST': 'psqldb',
            'PORT': 5432,
        }
    }
else:
    print('여기')
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': 'airhelperdev',
            'USER': 'airhelper',
            'PASSWORD': 'airhelper',
            'HOST': 'localhost',
            'PORT': 5432,
        }
    }
