# Generated by Django 3.1.3 on 2021-08-13 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0002_attendeduser'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendeduser',
            name='team',
            field=models.CharField(default='레드팀', max_length=20, verbose_name='팀'),
        ),
    ]
