# Generated by Django 3.1.3 on 2021-08-13 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0003_attendeduser_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendeduser',
            name='is_admin',
            field=models.BooleanField(default=False, verbose_name='방장 여부'),
        ),
    ]
