# Generated by Django 3.1.3 on 2021-05-11 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('user_id', models.CharField(max_length=50, unique=True, verbose_name='아이디')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='이메일')),
                ('name', models.CharField(max_length=60, verbose_name='이름')),
                ('call_sign', models.CharField(max_length=60, unique=True, verbose_name='콜사인')),
                ('profile_image', models.TextField(verbose_name='프로필사진')),
                ('is_active', models.BooleanField(default=True, verbose_name='계정 활성화여부')),
                ('is_staff', models.BooleanField(default=False, verbose_name='필드 관리자 여부')),
                ('is_admin', models.BooleanField(default=False, verbose_name='총 관리자 여부')),
                ('reg_date', models.DateTimeField(auto_now_add=True, verbose_name='가입일')),
            ],
            options={
                'verbose_name': '유저',
                'verbose_name_plural': '유저들',
                'db_table': 'custom_user',
                'ordering': ['reg_date'],
            },
        ),
    ]
