# Generated by Django 3.1.3 on 2021-07-05 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cert', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='profile_image',
            field=models.ImageField(blank=True, default='default_img.jpg', upload_to='profiles', verbose_name='프로필사진'),
        ),
    ]
