# Generated by Django 3.1.3 on 2021-08-21 07:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('room', '0004_attendeduser_is_admin'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20, unique=True, verbose_name='제목')),
                ('password', models.CharField(default='none', max_length=6, verbose_name='비밀번호')),
                ('verbose_left', models.IntegerField(default=0, verbose_name='레드팀 수')),
                ('verbose_right', models.IntegerField(default=0, verbose_name='블루팀 수')),
                ('time', models.IntegerField(default=0, verbose_name='게임 시간')),
                ('game_type', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='room.gametype', verbose_name='게임종류')),
            ],
            options={
                'verbose_name': '게임',
                'db_table': 'game',
            },
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team', models.CharField(default='레드팀', max_length=20, verbose_name='팀')),
                ('is_admin', models.BooleanField(default=False, verbose_name='방장 여부')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.game', verbose_name='게임ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='회원id')),
            ],
            options={
                'verbose_name': '플레이어',
                'db_table': 'player',
            },
        ),
    ]
