# Generated by Django 3.1.3 on 2021-06-01 10:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('social_user_id', models.CharField(max_length=100, unique=True, verbose_name='소셜서버에 등록된 회원번호')),
                ('social_type', models.CharField(choices=[('kakao', '카카오'), ('naver', '네이버')], max_length=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='socialuser', to=settings.AUTH_USER_MODEL, verbose_name='회원id')),
            ],
            options={
                'verbose_name': '소셜유저 정보',
                'db_table': 'socialuser',
                'unique_together': {('social_user_id', 'social_type', 'user')},
            },
        ),
    ]
